import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { 
      flex: 1,
    },
    backgroundGradient: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
    },
    scrollContent: {
      paddingBottom: 140,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 60,
      marginBottom: 24,
    },
    headerLeft: {
      flex: 1,
    },
    helloText: { 
      fontSize: 18,
      fontWeight: '500',
    },
    nameText: { 
      fontSize: 24, 
      fontWeight: "800",
      marginTop: 4,
      letterSpacing: -0.5,
    },
    avatarContainer: {
      borderRadius: 28,
      padding: 4,
      position: 'relative',
    },
    avatar: { 
      width: 48, 
      height: 48, 
      borderRadius: 24,
    },
    onlineIndicator: {
      position: 'absolute',
      bottom: 4,
      right: 4,
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: '#4ECDC4',
      borderWidth: 2,
      borderColor: '#fff',
    },
    balanceCard: {
      marginHorizontal: 20,
      borderRadius: 24,
      marginBottom: 32,
      shadowColor: '#667eea',
      shadowOffset: {
        width: 0,
        height: 12,
      },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 15,
    },
    balanceContent: {
      padding: 24,
      borderRadius: 24,
    },
    balanceHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    cardTitle: { 
      fontSize: 16,
      color: 'rgba(255,255,255,0.9)',
      fontWeight: '600',
    },
    amount: { 
      fontSize: 42, 
      fontWeight: "900",
      color: '#fff',
      marginBottom: 16,
      letterSpacing: -2,
    },
    balanceFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    changeIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(78, 205, 196, 0.2)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 12,
    },
    changeText: {
      color: '#4ECDC4',
      fontSize: 14,
      fontWeight: '600',
      marginLeft: 4,
    },
    viewDetailsBtn: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    viewDetailsText: {
      color: 'rgba(255,255,255,0.8)',
      fontSize: 14,
      fontWeight: '600',
      marginRight: 4,
    },
    quickStatsContainer: {
      marginBottom: 32,
    },
    sectionTitle: { 
      fontSize: 20, 
      fontWeight: "700",
      marginBottom: 16,
      paddingHorizontal: 20,
      letterSpacing: -0.5,
    },
    categoryList: {
      paddingHorizontal: 16,
    },
    categoryCard: {
      width: 120,
      padding: 16,
      borderRadius: 20,
      marginHorizontal: 4,
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    categoryIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    categoryName: {
      fontSize: 12,
      fontWeight: '600',
      marginBottom: 4,
    },
    categoryAmount: {
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 8,
    },
    progressBar: {
      width: '100%',
      height: 4,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      borderRadius: 2,
      marginBottom: 4,
    },
    progressFill: {
      height: '100%',
      borderRadius: 2,
    },
    categoryPercent: {
      fontSize: 10,
      fontWeight: '500',
    },
    expensesContainer: {
      paddingHorizontal: 20,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    seeAllText: {
      color: '#667eea',
      fontSize: 14,
      fontWeight: '600',
    },
    expenseCard: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 16,
      borderRadius: 20,
      marginBottom: 12,
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    expenseLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    iconContainer: {
      width: 48,
      height: 48,
      borderRadius: 24,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    expenseInfo: {
      flex: 1,
    },
    expenseTitle: { 
      fontSize: 16, 
      fontWeight: "600",
      marginBottom: 4,
    },
    categoryRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    expenseCategory: { 
      fontSize: 12,
      fontWeight: '500',
    },
    expenseTime: {
      fontSize: 12,
      fontWeight: '400',
      marginLeft: 4,
    },
    expenseRight: {
      alignItems: 'flex-end',
      flexDirection: 'row',
      // alignItems: 'center',
    },
    expenseAmount: { 
      fontSize: 16, 
      fontWeight: "700",
      marginRight: 8,
    },
    fabContainer: {
      position: "absolute",
      right: 20,
      bottom: 100,
    },
    fab: {
      borderRadius: 28,
      shadowColor: '#FF6B6B',
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 8,
    },
    fabContent: {
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: 'center',
      alignItems: 'center',
    },
    quickActions: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingVertical: 16,
      paddingHorizontal: 20,
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderTopWidth: 1,
      borderTopColor: 'rgba(255, 255, 255, 0.1)',
    },
    quickAction: {
      alignItems: 'center',
    },
    quickActionIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 4,
    },
    quickActionText: {
      fontSize: 12,
      fontWeight: '600',
    },
  });