import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#000',
    },
    backgroundGradient: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
    },
    floatingCircle: {
      position: 'absolute',
      borderRadius: 100,
      opacity: 0.1,
    },
    circle1: {
      width: 150,
      height: 150,
      backgroundColor: '#FFE066',
      top: 80,
      left: -30,
    },
    circle2: {
      width: 100,
      height: 100,
      backgroundColor: '#FF6B6B',
      top: 200,
      right: -20,
    },
    circle3: {
      width: 80,
      height: 80,
      backgroundColor: '#fff',
      bottom: 200,
      left: 30,
    },
    keyboardContainer: {
      flex: 1,
    },
    contentContainer: {
      flex: 1,
      paddingHorizontal: 24,
      paddingTop: 80,
      paddingBottom: 40,
      justifyContent: 'center',
    },
    headerContainer: {
      borderRadius: 20,
      padding: 24,
      marginBottom: 32,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 10,
      },
      shadowOpacity: 0.25,
      shadowRadius: 20,
      elevation: 10,
    },
    welcomeSection: {
      alignItems: 'center',
    },
    welcomeText: {
      fontSize: 18,
      color: 'rgba(255, 255, 255, 0.9)',
      fontWeight: '600',
    },
    title: {
      fontSize: 32,
      fontWeight: '800',
      color: '#fff',
      textAlign: 'center',
      marginTop: 8,
      letterSpacing: -1,
    },
    subtitle: {
      fontSize: 16,
      color: 'rgba(255, 255, 255, 0.7)',
      textAlign: 'center',
      marginTop: 8,
    },
    formContainer: {
      borderRadius: 20,
      padding: 24,
      marginBottom: 24,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 5,
      },
      shadowOpacity: 0.15,
      shadowRadius: 15,
      elevation: 8,
    },
    inputWrapper: {
      marginBottom: 20,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.2)',
      paddingHorizontal: 16,
      paddingVertical: 4,
    },
    inputFocused: {
      borderColor: '#667eea',
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      shadowColor: '#667eea',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 5,
    },
    inputIcon: {
      marginRight: 12,
    },
    input: {
      flex: 1,
      fontSize: 16,
      color: '#fff',
      paddingVertical: 16,
      fontWeight: '500',
    },
    passwordInput: {
      paddingRight: 50,
    },
    eyeIcon: {
      position: 'absolute',
      right: 16,
      padding: 4,
    },
    forgotPassword: {
      alignSelf: 'flex-end',
      marginTop: 8,
    },
    forgotText: {
      color: 'rgba(255, 255, 255, 0.8)',
      fontSize: 14,
      fontWeight: '500',
    },
    buttonSection: {
      width: '100%',
    },
    loginButton: {
      borderRadius: 16,
      marginBottom: 24,
      shadowColor: '#FF6B6B',
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 8,
    },
    loginGradient: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 18,
      paddingHorizontal: 32,
      borderRadius: 16,
    },
    loginText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: '700',
      marginHorizontal: 12,
    },
    buttonEmoji: {
      fontSize: 18,
    },
    dividerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 24,
    },
    divider: {
      flex: 1,
      height: 1,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    dividerText: {
      color: 'rgba(255, 255, 255, 0.6)',
      fontSize: 14,
      marginHorizontal: 16,
      fontWeight: '500',
    },
    googleButton: {
      borderRadius: 16,
      marginBottom: 24,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    googleBlur: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 16,
      paddingHorizontal: 32,
      borderRadius: 16,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
    },
    googleText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      marginLeft: 12,
    },
    signupContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    signupText: {
      color: 'rgba(255, 255, 255, 0.7)',
      fontSize: 16,
      fontWeight: '500',
    },
    signupLink: {
      color: '#FFE066',
      fontSize: 16,
      fontWeight: '700',
    },
  });